export enum MatchEventType {
  GOAL = 'GOAL',
  YELLOW_CARD = 'YELLOW_CARD',
  RED_CARD = 'RED_CARD',
  SUBSTITUTION = 'SUBSTITUTION',
  FOUL = 'FOUL',
  SHOT = 'SHOT',
  PERIOD_START = 'PERIOD_START',
  PERIOD_END = 'PERIOD_END',
}
